"""dserver_client package."""

from datetime import date, datetime

import click
import json
import logging

import pygments
import pygments.lexers
import pygments.formatters

import dtoolcore
import dtoolcore.utils
import dtool_config.cli
import dtool_lookup_api


logger = logging.getLogger(__name__)


# workaround for diverging python versions:
try:
    from importlib.metadata import version, PackageNotFoundError
    logger.debug("imported version, PackageNotFoundError from importlib.metadata")
except ModuleNotFoundError:
    from importlib_metadata import version, PackageNotFoundError
    logger.debug("imported version, PackageNotFoundError from importlib_metadata")

# first, try to determine dynamic version at runtime
try:
    __version__ = version(__name__)
    logger.debug("Determined version %s via importlib_metadata.version", __version__)
except PackageNotFoundError:
    # if that fails, check for static version file written by setuptools_scm
    try:
        from .version import version as __version__
        logger.debug("Determined version %s from autogenerated dserver_client/version.py", __version__)
    except:
        logger.debug("All efforts to determine version failed.")
        __version__ = None


DSERVER_URL_KEY = "DSERVER_URL"
DSERVER_TOKEN_KEY = "DSERVER_TOKEN"


def json_serial(obj):
    if isinstance(obj, (datetime, date)):
        return obj.isoformat()
    raise TypeError("Type {} not serializable".format(type(obj)))


def uris_from_lookup_response(response):
    """Return list of URIs from  response from /lookup_datasets/<uuid>."""
    return [item["uri"] for item in response]


def urljoin(*args):
    parts = []
    for p in args:
        if p.endswith("/"):
            p = p[:-1]
        parts.append(p)
    return "/".join(parts)


@click.command()
@click.argument("uuid")
def lookup(uuid):
    """Print the URIs associated with a UUID in the lookup server."""
    r = dtool_lookup_api.lookup(uuid)
    for uri in uris_from_lookup_response(r):
        click.secho(uri)


@click.command()
@click.argument("keyword", default="")
def search(keyword):
    """Print metadata matching keyword(s) on the lookup server."""
    r = dtool_lookup_api.search(keyword)
    formatted_json = json.dumps(r, indent=2)
    colorful_json = pygments.highlight(
        formatted_json,
        pygments.lexers.JsonLexer(),
        pygments.formatters.TerminalFormatter())

    click.secho(colorful_json, nl=False)


@click.command()
@click.argument("query", default="")
def query(query):
    """Print metadata associated with a query in the lookup server."""
    r = dtool_lookup_api.query(query)
    formatted_json = json.dumps(r, indent=2)
    colorful_json = pygments.highlight(
        formatted_json,
        pygments.lexers.JsonLexer(),
        pygments.formatters.TerminalFormatter())

    click.secho(colorful_json, nl=False)


#############################################################################
# Add click group to 'dtool config' with options for configuring connection
# to dserver.
#############################################################################

@dtool_config.cli.config.group()
def lookup_server():
    """Configure dserver connection."""


@lookup_server.command()
@click.argument("dserver_url", required=False)
def url(dserver_url):
    """Display / set / update URL for dserver."""
    if dserver_url is None:
        click.secho(dtoolcore.utils.get_config_value_from_file(
            DSERVER_URL_KEY, default=""
        ))
    else:
        click.secho(dtoolcore.utils.write_config_value_to_file(
            DSERVER_URL_KEY,
            dserver_url
        ))


@lookup_server.command()
@click.argument("dserver_token", required=False)
def token(dserver_token):
    """Display / set / update token for dserver."""
    if dserver_token is None:
        click.secho(dtoolcore.utils.get_config_value_from_file(
            DSERVER_TOKEN_KEY, default=""
        ))
    else:
        click.secho(dtoolcore.utils.write_config_value_to_file(
            DSERVER_TOKEN_KEY,
            dserver_token
        ))
